#!/bin/bash

mkdir -p icons

1>&2 echo

for i in $(seq -w 360); do
    1>&2 echo -e "\033[A$i / 360"
    if [ ! -f icons/loading_$i.svg ]; then
        python3 gen_loading.py icons/loading_$i.svg 256 100 $i
    fi
    if [ ! -f icons/loading_$i.ico ]; then
        convert -background none icons/loading_$i.svg icons/loading_$i.ico
    fi
done

for i in $(seq 360); do
    printf '%d ICON "icons/loading_%03d.ico"\n' $(( 10000 + i )) $i
done
